### ISSUE TITLE
Error updating from v17.0.1 to 20.0.2

### ISSUE THREAD

**Issue by marc-farre** [njsubedi/cloudron-keycloak#7]
@njsubedi have you got an idea of what could cause the error when updating the container?

I've created a Docker image with the latest version: https://hub.docker.com/layers/funkycram/org.keycloak.cloudronapp/20230109-104156-1845bd057/images/sha256-d669630828f97a77ce0a9d3afbfdf44ebd89f958a781fe3ad2422ca8ce506c71?context=repo

And doing `cloudron update`, "Wait for health check" nether succeeds:
```
 => Waiting for app to be updated 
 => Queued 
 => Cleaning up old install .........
 => Wait for health check ..............................................................................
```

Checking the logs, I have:
```
Healtheck error: Error: connect ECONNREFUSED 172.18.16.74:80802023-01-09T11:31:50.000Z DELETE 10
```

Thanks! Marc.

Full log:
```
Jan 09 12:31:38 box:settings initCache: pre-load settings
Jan 09 12:31:38 box:taskworker Starting task 5719. Logs are at /home/yellowtent/platformdata/logs/e7452131-a8f0-4cc1-821b-ad9536fd3c1d/apptask.log
Jan 09 12:31:38 box:apptask run: startTask installationState: pending_update runState: running
Jan 09 12:31:38 box:tasks update 5719: {"percent":5,"message":"Verify manifest"}
Jan 09 12:31:38 box:tasks update 5719: {"percent":25,"message":"Downloading image"}
Jan 09 12:31:38 box:docker downloadImage funkycram/org.keycloak.cloudronapp:20230109-104156-1845bd057
Jan 09 12:31:38 box:tasks update 5719: {"percent":35,"message":"Cleaning up old install"}
Jan 09 12:31:38 box:apptask deleteContainer: deleting app containers (app, scheduler)
Jan 09 12:31:38 box:shell removeLogrotateConfig spawn: /usr/bin/sudo -S /home/yellowtent/box/src/scripts/configurelogrotate.sh remove e7452131-a8f0-4cc1-821b-ad9536fd3c1d
Jan 09 12:31:49 box:services teardownAddons: Tearing down []
Jan 09 12:31:49 box:tasks update 5719: {"percent":45,"message":"Downloading icon"}
Jan 09 12:31:49 box:tasks update 5719: {"percent":60,"message":"Updating addons"}
Jan 09 12:31:49 box:services setupAddons: Setting up ["localstorage","postgresql","sendmail","ldap"]
Jan 09 12:31:49 box:services setupAddons: setting up addon localstorage with options {}
Jan 09 12:31:49 box:services setupLocalStorage
Jan 09 12:31:49 box:shell createVolume spawn: /usr/bin/sudo -S /home/yellowtent/box/src/scripts/mkdirvolume.sh /home/yellowtent/appsdata/e7452131-a8f0-4cc1-821b-ad9536fd3c1d/data
Jan 09 12:31:49 box:services setupAddons: setting up addon postgresql with options {}
Jan 09 12:31:49 box:services Setting up postgresql
Jan 09 12:31:49 box:services Setting postgresql addon config to [{"name":"CLOUDRON_POSTGRESQL_URL","value":"postgres://usere7452131a8f04cc1821bad9536fd3c1d:f107452533888d0e134dae5f3f6bdece3832962eec05ac88940e1f00b0ce9e69268d80815c497d56121cc63e6ec82e4197f3da9698ed1e8cc04dee3cdf86f8ac@postgresql/dbe7452131a8f04cc1821bad9536fd3c1d"},{"name":"CLOUDRON_POSTGRESQL_USERNAME","value":"usere7452131a8f04cc1821bad9536fd3c1d"},{"name":"CLOUDRON_POSTGRESQL_PASSWORD","value":"f107452533888d0e134dae5f3f6bdece3832962eec05ac88940e1f00b0ce9e69268d80815c497d56121cc63e6ec82e4197f3da9698ed1e8cc04dee3cdf86f8ac"},{"name":"CLOUDRON_POSTGRESQL_HOST","value":"postgresql"},{"name":"CLOUDRON_POSTGRESQL_PORT","value":"5432"},{"name":"CLOUDRON_POSTGRESQL_DATABASE","value":"dbe7452131a8f04cc1821bad9536fd3c1d"}]
Jan 09 12:31:49 box:services setupAddons: setting up addon sendmail with options {"supportsDisplayName":true}
Jan 09 12:31:49 box:services Setting up SendMail
Jan 09 12:31:49 box:services Setting sendmail addon config to [{"name":"CLOUDRON_MAIL_SMTP_SERVER","value":"mail"},{"name":"CLOUDRON_MAIL_SMTP_PORT","value":"2525"},{"name":"CLOUDRON_MAIL_SMTPS_PORT","value":"2465"},{"name":"CLOUDRON_MAIL_STARTTLS_PORT","value":"2587"},{"name":"CLOUDRON_MAIL_SMTP_USERNAME","value":"platform@transition-space.org"},{"name":"CLOUDRON_MAIL_SMTP_PASSWORD","value":"3330c9b84eccbef78b821ce772e51176813eb8bd643e1740"},{"name":"CLOUDRON_MAIL_FROM","value":"platform@transition-space.org"},{"name":"CLOUDRON_MAIL_DOMAIN","value":"transition-space.org"},{"name":"CLOUDRON_MAIL_FROM_DISPLAY_NAME","value":""}]
Jan 09 12:31:49 box:services setupAddons: setting up addon ldap with options {}
Jan 09 12:31:49 box:services Setting up LDAP
Jan 09 12:31:49 box:tasks update 5719: {"percent":70,"message":"Creating container"}
Jan 09 12:31:49 box:apptask createContainer: creating container
Jan 09 12:31:49 box:shell addLogrotateConfig spawn: /usr/bin/sudo -S /home/yellowtent/box/src/scripts/configurelogrotate.sh add e7452131-a8f0-4cc1-821b-ad9536fd3c1d /tmp/e7452131-a8f0-4cc1-821b-ad9536fd3c1d.logrotate
Jan 09 12:31:49 box:apptask startApp: starting container
Jan 09 12:31:49 box:tasks update 5719: {"percent":90,"message":"Configuring reverse proxy"}
Jan 09 12:31:49 box:tasks update 5719: {"percent":100,"message":"Done"}
Jan 09 12:31:49 box:taskworker Task took 11.19 seconds
Jan 09 12:31:49 box:tasks setCompleted - 5719: {"result":null,"error":null}
Jan 09 12:31:49 box:tasks update 5719: {"percent":100,"result":null,"error":null}
Jan 09 12:28:50 2023-01-09 11:28:50,606 INFO [io.quarkus] (main) Installed features: [agroal, cdi, hibernate-orm, infinispan-client, jdbc-h2, jdbc-mariadb, jdbc-mssql, jdbc-mysql, jdbc-oracle, jdbc-postgresql, keycloak, narayana-jta, reactive-routes, resteasy, resteasy-jackson, smallrye-context-propagation, smallrye-health, smallrye-metrics, vault, vertx]
Jan 09 12:31:48
Jan 09 12:31:49 Setting ENV variables to /app/data/conf/keycloak.conf
Healtheck error: Error: connect ECONNREFUSED 172.18.16.74:80802023-01-09T11:31:50.000Z DELETE 10
Jan 09 12:31:50 SMTP enabled. Setting up SMTP Server values...
Jan 09 12:31:50 INSERT 0 1
Jan 09 12:31:50 INSERT 0 1
Jan 09 12:31:50 INSERT 0 1
Jan 09 12:31:50 INSERT 0 1
Jan 09 12:31:50 INSERT 0 1
Jan 09 12:31:50 INSERT 0 1
Jan 09 12:31:50 INSERT 0 1
Jan 09 12:31:50 INSERT 0 1
Jan 09 12:31:50 INSERT 0 1
Jan 09 12:31:50 INSERT 0 1
Jan 09 12:31:50 JAVA_OPTS_APPEND: -XX:MaxRAM=8796093022207M
Jan 09 12:31:50 Appending additional Java properties to JAVA_OPTS: -XX:MaxRAM=8796093022207M
Jan 09 12:31:54 2023-01-09 11:31:52,602 INFO [org.keycloak.quarkus.runtime.hostname.DefaultHostnameProvider] (main) Hostname settings: Base URL: <unset>, Hostname: keycloak-test.transition-space.org, Strict HTTPS: true, Path: <request>, Strict BackChannel: false, Admin URL: <unset>, Admin: <request>, Port: -1, Proxied: true
Jan 09 12:31:54 2023-01-09 11:31:54,409 WARN [io.quarkus.agroal.runtime.DataSources] (main) Datasource <default> enables XA but transaction recovery is not enabled. Please enable transaction recovery by setting quarkus.transaction-manager.enable-recovery=true, otherwise data may be lost if the application is terminated abruptly
Jan 09 12:31:55 2023-01-09 11:31:55,642 WARN [org.infinispan.CONFIG] (keycloak-cache-init) ISPN000569: Unable to persist Infinispan internal caches as no global state enabled
Jan 09 12:31:55 2023-01-09 11:31:55,678 WARN [org.infinispan.PERSISTENCE] (keycloak-cache-init) ISPN000554: jboss-marshalling is deprecated and planned for removal
Jan 09 12:31:55 2023-01-09 11:31:55,692 INFO [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000556: Starting user marshaller 'org.infinispan.jboss.marshalling.core.JBossUserMarshaller'
Jan 09 12:31:56 2023-01-09 11:31:56,004 INFO [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000128: Infinispan version: Infinispan 'Triskaidekaphobia' 13.0.10.Final
Jan 09 12:31:56 2023-01-09 11:31:56,120 INFO [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000078: Starting JGroups channel `ISPN`
Jan 09 12:31:56 2023-01-09 11:31:56,120 INFO [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000088: Unable to use any JGroups configuration mechanisms provided in properties {}. Using default JGroups configuration!
Jan 09 12:31:56 2023-01-09 11:31:56,254 INFO [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000094: Received new cluster view for channel ISPN: [1e2f4fad-dcac-459b-9d6a-21a45ae64d98-10121|38] (3) [1e2f4fad-dcac-459b-9d6a-21a45ae64d98-10121, f7c72696-5ad7-4386-8b52-e19cd8b2cf76-46908, e7452131-a8f0-4cc1-821b-ad9536fd3c1d-38002]
Jan 09 12:31:56 2023-01-09 11:31:56,259 INFO [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000079: Channel `ISPN` local address is `e7452131-a8f0-4cc1-821b-ad9536fd3c1d-38002`, physical addresses are `[172.18.16.74:58572]`
Jan 09 12:31:56 2023-01-09 11:31:56,601 WARN [org.infinispan.statetransfer.InboundTransferTask] (jgroups-9,e7452131-a8f0-4cc1-821b-ad9536fd3c1d-38002) ISPN000210: Failed to request state of cache authenticationSessions from node 1e2f4fad-dcac-459b-9d6a-21a45ae64d98-10121, segments {15-38 132-150 153-181 238-255}: org.infinispan.commons.CacheException: ExceptionResponse(java.lang.IllegalArgumentException: Segments must not be null or empty)
Jan 09 12:31:56 at org.infinispan.statetransfer.InboundTransferTask.lambda$startTransfer$3(InboundTransferTask.java:167)
Jan 09 12:31:56 at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:930)
Jan 09 12:31:56 at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:907)
Jan 09 12:31:56 at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
Jan 09 12:31:56 at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073)
Jan 09 12:31:56 at org.infinispan.remoting.transport.AbstractRequest.complete(AbstractRequest.java:67)
Jan 09 12:31:56 at org.infinispan.remoting.transport.impl.SingleTargetRequest.onResponse(SingleTargetRequest.java:46)
Jan 09 12:31:56 at org.infinispan.remoting.transport.impl.RequestRepository.addResponse(RequestRepository.java:51)
Jan 09 12:31:56 at org.infinispan.remoting.transport.jgroups.JGroupsTransport.processResponse(JGroupsTransport.java:1496)
Jan 09 12:31:56 at org.infinispan.remoting.transport.jgroups.JGroupsTransport.processMessage(JGroupsTransport.java:1398)
Jan 09 12:31:56 at org.infinispan.remoting.transport.jgroups.JGroupsTransport.access$300(JGroupsTransport.java:146)
Jan 09 12:31:56 at org.infinispan.remoting.transport.jgroups.JGroupsTransport$ChannelCallbacks.up(JGroupsTransport.java:1586)
Jan 09 12:31:56 at org.jgroups.JChannel.up(JChannel.java:780)
Jan 09 12:31:56 at org.jgroups.stack.ProtocolStack.up(ProtocolStack.java:913)
Jan 09 12:31:56 at org.jgroups.protocols.FRAG3.up(FRAG3.java:165)
Jan 09 12:31:56 at org.jgroups.protocols.FlowControl.up(FlowControl.java:347)
Jan 09 12:31:56 at org.jgroups.protocols.FlowControl.up(FlowControl.java:347)
Jan 09 12:31:56 at org.jgroups.protocols.pbcast.GMS.up(GMS.java:876)
Jan 09 12:31:56 at org.jgroups.protocols.pbcast.STABLE.up(STABLE.java:254)
Jan 09 12:31:56 at org.jgroups.protocols.UNICAST3.deliverMessage(UNICAST3.java:1048)
Jan 09 12:31:56 at org.jgroups.protocols.UNICAST3.addMessage(UNICAST3.java:771)
Jan 09 12:31:56 at org.jgroups.protocols.UNICAST3.handleDataReceived(UNICAST3.java:752)
Jan 09 12:31:56 at org.jgroups.protocols.UNICAST3.up(UNICAST3.java:405)
Jan 09 12:31:56 at org.jgroups.protocols.pbcast.NAKACK2.up(NAKACK2.java:592)
Jan 09 12:31:56 at org.jgroups.protocols.VERIFY_SUSPECT.up(VERIFY_SUSPECT.java:132)
Jan 09 12:31:56 at org.jgroups.protocols.FailureDetection.up(FailureDetection.java:186)
Jan 09 12:31:56 at org.jgroups.protocols.FD_SOCK.up(FD_SOCK.java:254)
Jan 09 12:31:56 at org.jgroups.protocols.MERGE3.up(MERGE3.java:281)
Jan 09 12:31:56 at org.jgroups.protocols.Discovery.up(Discovery.java:300)
Jan 09 12:31:56 at org.jgroups.protocols.TP.passMessageUp(TP.java:1400)
Jan 09 12:31:56 at org.jgroups.util.SubmitToThreadPool$SingleMessageHandler.run(SubmitToThreadPool.java:98)
Jan 09 12:31:56 at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
Jan 09 12:31:56 at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
Jan 09 12:31:56 at java.base/java.lang.Thread.run(Thread.java:829)
Jan 09 12:31:56
Jan 09 12:31:56 2023-01-09 11:31:56,613 WARN [org.infinispan.statetransfer.InboundTransferTask] (jgroups-9,e7452131-a8f0-4cc1-821b-ad9536fd3c1d-38002) ISPN000210: Failed to request state of cache authenticationSessions from node f7c72696-5ad7-4386-8b52-e19cd8b2cf76-46908, segments {7-14 73-113 130-131 205-237}: org.infinispan.commons.CacheException: ExceptionResponse(java.lang.IndexOutOfBoundsException: bitIndex < 0: -2)
Jan 09 12:31:56 at org.infinispan.statetransfer.InboundTransferTask.lambda$startTransfer$3(InboundTransferTask.java:167)
Jan 09 12:31:56 at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:930)
Jan 09 12:31:56 at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:907)
Jan 09 12:31:56 at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
Jan 09 12:31:56 at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073)
Jan 09 12:31:56 at org.infinispan.remoting.transport.AbstractRequest.complete(AbstractRequest.java:67)
Jan 09 12:31:56 at org.infinispan.remoting.transport.impl.SingleTargetRequest.onResponse(SingleTargetRequest.java:46)
Jan 09 12:31:56 at org.infinispan.remoting.transport.impl.RequestRepository.addResponse(RequestRepository.java:51)
Jan 09 12:31:56 at org.infinispan.remoting.transport.jgroups.JGroupsTransport.processResponse(JGroupsTransport.java:1496)
Jan 09 12:31:56 at org.infinispan.remoting.transport.jgroups.JGroupsTransport.processMessage(JGroupsTransport.java:1398)
Jan 09 12:31:56 at org.infinispan.remoting.transport.jgroups.JGroupsTransport.access$300(JGroupsTransport.java:146)
Jan 09 12:31:56 at org.infinispan.remoting.transport.jgroups.JGroupsTransport$ChannelCallbacks.up(JGroupsTransport.java:1586)
Jan 09 12:31:56 at org.jgroups.JChannel.up(JChannel.java:780)
Jan 09 12:31:56 at org.jgroups.stack.ProtocolStack.up(ProtocolStack.java:913)
Jan 09 12:31:56 at org.jgroups.protocols.FRAG3.up(FRAG3.java:165)
Jan 09 12:31:56 at org.jgroups.protocols.FlowControl.up(FlowControl.java:347)
Jan 09 12:31:56 at org.jgroups.protocols.FlowControl.up(FlowControl.java:347)
Jan 09 12:31:56 at org.jgroups.protocols.pbcast.GMS.up(GMS.java:876)
Jan 09 12:31:56 at org.jgroups.protocols.pbcast.STABLE.up(STABLE.java:254)
Jan 09 12:31:56 at org.jgroups.protocols.UNICAST3.deliverMessage(UNICAST3.java:1048)
Jan 09 12:31:56 at org.jgroups.protocols.UNICAST3.addMessage(UNICAST3.java:771)
Jan 09 12:31:56 at org.jgroups.protocols.UNICAST3.handleDataReceived(UNICAST3.java:752)
Jan 09 12:31:56 at org.jgroups.protocols.UNICAST3.up(UNICAST3.java:405)
Jan 09 12:31:56 at org.jgroups.protocols.pbcast.NAKACK2.up(NAKACK2.java:592)
Jan 09 12:31:56 at org.jgroups.protocols.VERIFY_SUSPECT.up(VERIFY_SUSPECT.java:132)
Jan 09 12:31:56 at org.jgroups.protocols.FailureDetection.up(FailureDetection.java:186)
Jan 09 12:31:56 at org.jgroups.protocols.FD_SOCK.up(FD_SOCK.java:254)
Jan 09 12:31:56 at org.jgroups.protocols.MERGE3.up(MERGE3.java:281)
Jan 09 12:31:56 at org.jgroups.protocols.Discovery.up(Discovery.java:300)
Jan 09 12:31:56 at org.jgroups.protocols.TP.passMessageUp(TP.java:1400)
Jan 09 12:31:56 at org.jgroups.util.SubmitToThreadPool$SingleMessageHandler.run(SubmitToThreadPool.java:98)
Jan 09 12:31:56 at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
Jan 09 12:31:56 at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
Jan 09 12:31:56 at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by njsubedi** [comment]
Any update on the issue? Did you try another time? I don't think the ECONNREFUSED is related to this package, but an error thrown by Cloudron.

**Comment by marc-farre** [comment]
I've just tested with the latest 20.0.3 version and I still have the same problem.
Cloudron version: 7.3.4

What I do to update:
```
git clone https://github.com/njsubedi/cloudron-keycloak.git
cd cloudron-keycloak
docker login
cloudron build
cloudron update
```

After updating, the Cloudron container says: Package Version 20.0.3
So it works, but it cannot start because of this health check.
Thanks!

Log:
```
Healtheck error: Error: connect ECONNREFUSED 172.18.19.37:80802023-01-16T12:34:16.000Z 2023-01-16 12:34:13,589 INFO [org.keycloak.quarkus.runtime.hostname.DefaultHostnameProvider] (main) Hostname settings: Base URL: <unset>, Hostname: id-dev-nov.transition-space.org, Strict HTTPS: true, Path: <request>, Strict BackChannel: false, Admin URL: <unset>, Admin: <request>, Port: -1, Proxied: true
Jan 16 13:34:16 2023-01-16 12:34:15,893 WARN [io.quarkus.agroal.runtime.DataSources] (main) Datasource <default> enables XA but transaction recovery is not enabled. Please enable transaction recovery by setting quarkus.transaction-manager.enable-recovery=true, otherwise data may be lost if the application is terminated abruptly
Jan 16 13:34:17 2023-01-16 12:34:17,659 WARN [org.infinispan.CONFIG] (keycloak-cache-init) ISPN000569: Unable to persist Infinispan internal caches as no global state enabled
Jan 16 13:34:17 2023-01-16 12:34:17,667 WARN [org.infinispan.PERSISTENCE] (keycloak-cache-init) ISPN000554: jboss-marshalling is deprecated and planned for removal
Jan 16 13:34:17 2023-01-16 12:34:17,703 INFO [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000556: Starting user marshaller 'org.infinispan.jboss.marshalling.core.JBossUserMarshaller'
Jan 16 13:34:18 2023-01-16 12:34:18,172 INFO [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000128: Infinispan version: Infinispan 'Triskaidekaphobia' 13.0.10.Final
Jan 16 13:34:18 2023-01-16 12:34:18,372 INFO [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000078: Starting JGroups channel `ISPN`
Jan 16 13:34:18 2023-01-16 12:34:18,372 INFO [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000088: Unable to use any JGroups configuration mechanisms provided in properties {}. Using default JGroups configuration!
Jan 16 13:34:18 2023-01-16 12:34:18,554 INFO [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000094: Received new cluster view for channel ISPN: [f7c72696-5ad7-4386-8b52-e19cd8b2cf76-46908|42] (3) [f7c72696-5ad7-4386-8b52-e19cd8b2cf76-46908, e7452131-a8f0-4cc1-821b-ad9536fd3c1d-20411, 1e2f4fad-dcac-459b-9d6a-21a45ae64d98-32220]
Jan 16 13:34:18 2023-01-16 12:34:18,561 INFO [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000079: Channel `ISPN` local address is `1e2f4fad-dcac-459b-9d6a-21a45ae64d98-32220`, physical addresses are `[172.18.19.37:35486]`
Healtheck error: Error: connect ECONNREFUSED 172.18.19.37:80802023-01-16T12:34:20.000Z 2023-01-16 12:34:20,501 WARN [org.infinispan.statetransfer.InboundTransferTask] (jgroups-8,1e2f4fad-dcac-459b-9d6a-21a45ae64d98-32220) ISPN000210: Failed to request state of cache authenticationSessions from node f7c72696-5ad7-4386-8b52-e19cd8b2cf76-46908, segments {4-24 26 33-39 57-58 107-127 206-234}: org.infinispan.commons.CacheException: ExceptionResponse(java.io.EOFException)
Jan 16 13:34:20 at org.infinispan.statetransfer.InboundTransferTask.lambda$startTransfer$3(InboundTransferTask.java:167)
Jan 16 13:34:20 at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:930)
Jan 16 13:34:20 at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:907)
Jan 16 13:34:20 at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
Jan 16 13:34:20 at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073)
Jan 16 13:34:20 at org.infinispan.remoting.transport.AbstractRequest.complete(AbstractRequest.java:67)
Jan 16 13:34:20 at org.infinispan.remoting.transport.impl.SingleTargetRequest.onResponse(SingleTargetRequest.java:46)
Jan 16 13:34:20 at org.infinispan.remoting.transport.impl.RequestRepository.addResponse(RequestRepository.java:51)
Jan 16 13:34:20 at org.infinispan.remoting.transport.jgroups.JGroupsTransport.processResponse(JGroupsTransport.java:1496)
Jan 16 13:34:20 at org.infinispan.remoting.transport.jgroups.JGroupsTransport.processMessage(JGroupsTransport.java:1398)
Jan 16 13:34:20 at org.infinispan.remoting.transport.jgroups.JGroupsTransport.access$300(JGroupsTransport.java:146)
Jan 16 13:34:20 at org.infinispan.remoting.transport.jgroups.JGroupsTransport$ChannelCallbacks.up(JGroupsTransport.java:1586)
Jan 16 13:34:20 at org.jgroups.JChannel.up(JChannel.java:780)
Jan 16 13:34:20 at org.jgroups.stack.ProtocolStack.up(ProtocolStack.java:913)
Jan 16 13:34:20 at org.jgroups.protocols.FRAG3.up(FRAG3.java:165)
Jan 16 13:34:20 at org.jgroups.protocols.FlowControl.up(FlowControl.java:347)
Jan 16 13:34:20 at org.jgroups.protocols.FlowControl.up(FlowControl.java:347)
Jan 16 13:34:20 at org.jgroups.protocols.pbcast.GMS.up(GMS.java:876)
Jan 16 13:34:20 at org.jgroups.protocols.pbcast.STABLE.up(STABLE.java:254)
Jan 16 13:34:20 at org.jgroups.protocols.UNICAST3.deliverMessage(UNICAST3.java:1048)
Jan 16 13:34:20 at org.jgroups.protocols.UNICAST3.addMessage(UNICAST3.java:771)
Jan 16 13:34:20 at org.jgroups.protocols.UNICAST3.handleDataReceived(UNICAST3.java:752)
Jan 16 13:34:20 at org.jgroups.protocols.UNICAST3.up(UNICAST3.java:405)
Jan 16 13:34:20 at org.jgroups.protocols.pbcast.NAKACK2.up(NAKACK2.java:592)
Jan 16 13:34:20 at org.jgroups.protocols.VERIFY_SUSPECT.up(VERIFY_SUSPECT.java:132)
Jan 16 13:34:20 at org.jgroups.protocols.FailureDetection.up(FailureDetection.java:186)
Jan 16 13:34:20 at org.jgroups.protocols.FD_SOCK.up(FD_SOCK.java:254)
Jan 16 13:34:20 at org.jgroups.protocols.MERGE3.up(MERGE3.java:281)
Jan 16 13:34:20 at org.jgroups.protocols.Discovery.up(Discovery.java:300)
Jan 16 13:34:20 at org.jgroups.protocols.TP.passMessageUp(TP.java:1400)
Jan 16 13:34:20 at org.jgroups.util.SubmitToThreadPool$SingleMessageHandler.run(SubmitToThreadPool.java:98)
Jan 16 13:34:20 at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
Jan 16 13:34:20 at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
Jan 16 13:34:20 at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by njsubedi** [comment]
The problem is with the Redis addon. Are you sure redis service is running on your Cloudron?

**Comment by marc-farre** [comment]
Thanks for your investigation.
Yes, Redis seams to be working (page /#/services):
![image](https://user-images.githubusercontent.com/23310825/213189201-d19b62ab-bb97-4d8f-a26a-256e6feb1ddd.png)

What strange is that version 17 is working well.

**Comment by samuk** [comment]
@njsubedi do you have any ideas on how we could debug this further please?

**Comment by gramakri** [comment]
> Healtheck error: Error: connect ECONNREFUSED 172.18.16.74:80802023-01-09T11:31:50.000Z

This only means that the Cloudron healthcheck (internal service that polls if app is running) is unable to contact the app on port 8080. I guess either the app is not running at all or the port 8080 has changed to something else with the new version? If so, the CloudronManifest.json httpPort has to be changed accordingly.

**Comment by samuk** [comment]
Thanks @gramakri does the app build correctly for you?

**Comment by marc-farre** [comment]
Thanks @gramakri !
Yes, this is the problem.
How can I know the port? I've nether changed it.
If I open the file `conf/keycloak.conf` I have:
```
http-host = 0.0.0.0
http-port = 8080
```

Perhaps is it an IP address problem?

Tested again today, still have `Healtheck error: Error: connect ECONNREFUSED 172.18.20.56:8080`

In the log, I have:
![image](https://user-images.githubusercontent.com/23310825/232742540-2eff6f93-950f-483e-b131-23f9491f848e.png)
But even If I stop the app, I cannot start it as I always have this Healtheck error.
Thanks!

**Comment by marc-farre** [comment]
@njsubedi I have the same problem when installing a new instance, with `cloudron install -l keycloak.my-domain.tld`
Full process to reproduce:
```sh
git clone https://github.com/njsubedi/cloudron-keycloak.git
cd cloudron-keycloak
docker login
cloudron login my.my-domain.tld
cloudron build
cloudron install -l keycloak.my-domain.tld
```
